ARG DEMO_IMAGE
FROM ${DEMO_IMAGE}

COPY package.json /root
COPY package-lock.json /root
RUN npm ci
COPY ./deploy/run-*.sh /root
RUN chmod a+x run-*.sh
COPY cypress.json /root
COPY cypress /root/cypress
